name: CI

on:
  push:
  pull_request:
  # Prime the caches every Monday
  schedule:
    - cron: '14 3 * * MON'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
#          - 4.02.3
#          - 4.03.0
#          - 4.04.2
#          - 4.05.0
#          - 4.06.1
#          - 4.07.1
#          - 4.08.1
#          - 4.09.1
#          - 4.10.2
          - 4.11.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate date-based cache key
        id: key
        run: |
          # Put year and week number in steps.key.outputs.week
          # This command "works" for both PowerShell and POSIX shell
          echo ":$(Write-Output ':')set-output name=week::$(Get-Date -UFormat '%Y-%W')-"
          echo ":`echo :`set-output name=week::`date -u '+%Y-%W'`-"

      - name: opam Cache
        uses: actions/cache@v2
        with:
          path: .github/caches/opam
          key: ${{ runner.os }}-${{ steps.key.outputs.week }}3

      - name: compiler Cache
        uses: actions/cache@v2
        with:
          path: .github/caches/compiler
          key: ${{ runner.os }}-${{ matrix.ocaml-version}}-${{ steps.key.outputs.week }}3

      - name: build Cache
        uses: actions/cache@v2
        with:
          path: .github/caches/build
          key: ${{ runner.os }}-${{ matrix.ocaml-version}}-${{ steps.key.outputs.week }}3-${{ hashFiles('bitmasks.opam') }}

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: dra27/setup-ocaml@faster-ubuntu
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add bitmasks.dev . --no-action
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build @install @runtest
      - run: opam exec -- make doc
