name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
#          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.02.3
          - 4.03.0
          - 4.04.2
          - 4.05.0
          - 4.06.1
          - 4.07.1
          - 4.08.1
          - 4.09.1
          - 4.10.2
          - 4.11.1
        include:
          - os: windows-latest
            cache: D:\ocaml-cache
#          - os: macos-latest
#            cache: ~/.opam
          - os: ubuntu-latest
            cache: ~/.opam

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate date-based cache key (Unix)
        run: |
          # Put year and week number in cache-key
          date '+%Y-%W' > ./cache-key
        if: matrix.os != 'windows-latest'

      - name: Generate date-based cache key (Windows)
        run: |
          # Put year and week number in cache-key
          Write-Output '${{ matrix.cache }} - ${{ matrix.os }} - ${{ matrix.ocaml-version }}'
          Get-Date -UFormat '%Y-%W' | Out-File -FilePath .\cache-key
        if: matrix.os == 'windows-latest'

      - name: Cygwin Cache
        uses: actions/cache@v2
        with:
          path: D:\cygwin-cache
          key: cygwin-5-${{ hashFiles('cache-key') }}
        if: matrix.os == 'windows-latest'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.cache }}
          key: bitmasks-19-${{ matrix.os }}-${{ matrix.ocaml-version}}-${{ hashFiles('cache-key', 'bitmasks.opam') }}

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: dra27/setup-ocaml@caches
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add bitmasks.dev . --no-action
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build @install @runtest
      - run: opam exec -- make doc
